name: Sync Main Code

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main-repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "rohan-kadukar"
          git config --global user.email "rohankadukar123@gmail.com" # Optional but recommended

      - name: Push to copy-main-repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote add copy https://x-access-token:${GH_PAT}@github.com/rohan-kadukar/copy-main-repo.git
          git push copy HEAD:main --force
