name: Sync to copy-main-repo

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for pushing

      - name: Push code to copy-main-repo using PAT
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git config --global user.name "Rohan Kadukar"
          git config --global user.email "rohankadukar123@gmail.com"

          git remote add target https://x-access-token:${TARGET_REPO_PAT}@github.com/rohan-kadukar/copy-main-repo.git
          git push --force target main
